Update CI/CD with GitHub Action

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -20,7 +20,7 @@ jobs:
         with:
           submodules: recursive
 
-  build-and-test:
+  build:
     runs-on: ubuntu-latest
     needs: update-submodules
     steps:
@@ -33,27 +33,49 @@ jobs:
           java-version: '22'
           distribution: ''
 
-      - name: Build and Test All Services
+      - name: Build Services
         run: |
           if [ "${{ github.event.inputs.service }}" == "all" ]; then
             ./mvnw clean install
-            docker-compose -f docker-compose.yml up --build -d
           elif [ "${{ github.event.inputs.service }}" == "auth_service" ]; then
             cd auth_service
             ./mvnw clean install
-            docker-compose -f docker-compose.yml up --build -d auth-service
           elif [ "${{ github.event.inputs.service }}" == "file_service" ]; then
             cd file_service
             ./mvnw clean install
+          else
+            echo "Invalid service specified."
+            exit 1
+
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Run Unit Tests
+        run: |
+          if [ "${{ github.event.inputs.service }}" == "all" ]; then
+            docker-compose -f docker-compose.yml up --build -d
+          elif [ "${{ github.event.inputs.service }}" == "auth_service" ]; then
+            docker-compose -f docker-compose.yml up --build -d auth-service
+          elif [ "${{ github.event.inputs.service }}" == "file_service" ]; then
             docker-compose -f docker-compose.yml up --build -d file-service
           else
             echo "Invalid service specified."
             exit 1
-          fi
+
+      - name: Verify Unit Tests
+        run: |
+          docker-compose exec -T ${{ github.event.inputs.service }} ./mvnw test || echo "Tests failed"
+
+      - name: Stop Docker Containers
+        run: docker-compose down
 
   deploy:
     runs-on: ubuntu-latest
-    needs: build-and-test
+    needs: test
     steps:
       - name: Deploy Microservices
         run: |
@@ -66,4 +88,3 @@ jobs:
           else
             echo "Invalid service specified."
             exit 1
-          fi
